apiVersion: v1
kind: Pod
metadata:
  name: debian-utils
  namespace: pstastny
spec:
#  nodeSelector:
#    role-app: app

  containers:
    - name: debian-utils
      image: pstast/debian-utils
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo ok; sleep 10; done"]
